[package]
name = "wasm-crate"
version = "0.1.0"
edition = "2018"

[lib]
crate-type = ["cdylib", "rlib"]

[features]
default = ["console_error_panic_hook"]

[dependencies]
wasm-bindgen = "0.2.63"
web-sys = { version = "0.3.59", features = ['console'] }
js-sys = "0.3.59"

console_error_panic_hook = { version = "0.1.6", optional = true }
wee_alloc = { version = "0.4.5", optional = true }
serde-wasm-bindgen = "0.4.5"
serde = { version = "1.0.149", features = ["derive"] }

[dev-dependencies]
wasm-bindgen-test = "0.3.13"
cargo-watch = "8.1.2"

[profile.release]
opt-level = "s"
